package buildSrc.configurators.dependencies

internal object Version {
    const val kotlin = "1.5.31"
    const val realm = "10.10.1"
    const val gradle = "7.1.0"
    const val appCompat = "1.4.1"
    const val coreKtx = "1.7.0"
    const val composeActivity = "1.4.0"
    const val navigation = "2.4.0"
    const val dataStore = "1.0.0"
    const val compose = "1.0.5"
    const val composeConstraint = "1.0.0-beta02"
    const val accompanist = "0.24.1-alpha"
    const val lifecycle = "2.4.0"
    const val dagger = "2.40.5"
    const val timber = "4.7.1"
    const val serializationJson = "1.3.1"
    const val serializationConverter = "0.8.0"
    const val retrofit = "2.9.0"
    const val material = "1.4.0"
    const val okhttp = "4.9.3"
    const val coroutinesAndroid = "1.5.2"
    const val mockitoKotlin = "3.2.0"
    const val junit = "1.1.0"
}